replicaCount: 1

image:
  repository: 950165721116.dkr.ecr.ap-south-1.amazonaws.com/secure-gitops-app
  tag: "sha-8b9c855fb43cf92be8bfafc201b4acd05e1ee2d8"
  digest: ""
  pullPolicy: IfNotPresent

config:
  environment: staging
  forceFailure: "false"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70

serviceMonitor:
  # Enabled later after Prometheus Operator installs the ServiceMonitor CRD.
  enabled: false
  labels:
    release: monitoring

ingress:
  enabled: false
