replicaCount: 2

image:
  repository: 950165721116.dkr.ecr.ap-south-1.amazonaws.com/secure-gitops-app
  tag: "sha-fa41e2ae3720ee0f6886668195c9a783a71258a4"
  digest: ""
  pullPolicy: IfNotPresent

config:
  environment: production
  forceFailure: "false"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

serviceMonitor:
  # Enabled later after Prometheus Operator installs the ServiceMonitor CRD.
  enabled: false
  labels:
    release: monitoring

ingress:
  enabled: false
